# Site
title: "Devnspiration"
description: "Devnspiration é o lugar para inspiração diária de developers."
baseurl: ""
url: "https://devnspiration.com"
username: "devnspiration"

permalink: /blog/:title

menu:
  - title: "Blog"
    slug: "blog"

# Build
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: assets/_sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - README.md
  - LICENSE
